export const CARD_FORM_ACTIONS = {
  ADD_TEXT_QUILL: "ADD_TEXT_QUILL",
  ADD_MATH_QUILL: "ADD_MATH_QUILL",
  UPDATE_LATEX: "UPDATE_LATEX",
  UPDATE_HTML_CONTENT: "UPDATE_HTML_CONTENT",
  SET_FIELDS: "SET_FIELDS",
  RESET_FIELDS: "RESET_FIELDS",
}
