export const CARDS_ACTIONS = {
  FETCH_CARDS: "FETCH_CARDS",
  SET_MAIN_CARD: "SET_MAIN_CARD",
  ADD_TO_COLLECTION: "ADD_TO_COLLECTION",
  SET_TAGS: "SET_TAGS",
  SET_DIFFICULTIES: "SET_DIFFICULTIES",
  NEW_CARD: "NEW_CARD",
  UPDATE_CARD: "UPDATE_CARD",
  REMOVE_CARD: "REMOVE_CARD",
  RESET_CARDS: "RESET_CARDS",
};

export const CARD_FORM_ACTIONS = {
  ADD_TEXT_QUILL: "ADD_TEXT_QUILL",
  ADD_MATH_QUILL: "ADD_MATH_QUILL",
  UPDATE_LATEX: "UPDATE_LATEX",
  UPDATE_HTML_CONTENT: "UPDATE_HTML_CONTENT",
  SET_FIELDS: "SET_FIELDS",
}

export const FIELD_TYPE = {
  MATH: "MATH",
  TEXT: "TEXT",
}
